version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: ${SERVICE_RESTART}
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_HOST}
      - N8N_WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_HOST}
      - N8N_WEBHOOK_TUNNEL=${N8N_PROTOCOL}://${N8N_HOST}
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - N8N_RUNNERS_ENABLED=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - N8N_SERVE_STATIC_FROM_URL_PATH=/static
      - N8N_SERVE_STATIC_FROM_DIRECTORY=/static
    volumes:
      - n8n_data:/home/node/.n8n
      - ./static:/static
    networks:
      - n8n-network
    depends_on:
      - ngrok
  ngrok:
    image: ngrok/ngrok:latest
    restart: ${SERVICE_RESTART}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http n8n:${N8N_PORT} --domain=${N8N_HOST}"
    ports:
      - "4040:4040"
    networks:
      - n8n-network
networks:
  n8n-network:
    driver: bridge
volumes:
  n8n_data:
    driver: local
