version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: ${SERVICE_RESTART}
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_HOST}
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      - ngrok
  ngrok:
    image: ngrok/ngrok:latest
    restart: ${SERVICE_RESTART}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http n8n:5678 --domain=summary-super-mackerel.ngrok-free.app"
    ports:
      - "4040:4040"
    networks:
      - n8n-network
networks:
  n8n-network:
    driver: bridge
volumes:
  n8n_data:
    driver: local
